### ISSUE TITLE
More of a question & suggestion rather than an issue

### ISSUE THREAD

**Issue by star-krafter** [Slava0135/Seadustry#2]
Is the landfill block researchable in the campaign, if so then can you add a 'shallow' landfill block? It basically acts like the landfill block except it only creates a shallow block that allows you to collect water and build on it.

**Comment by Slava0135** [comment]
The mod wasn't designed to be used in campaign. With shallow block you could basically create sand tiles wherever you want so I don't know about that.

**Comment by star-krafter** [comment]
Also, maybe add a sand block for deeper waters, or you could probably make it so that you would need to place two landfill blocks instead of one for the 'landfill' block to reach the surface from deeper water.

**Comment by Jonathansvendsen** [comment]
There is no Sieve or collector in the mod its just the landfill

**Comment by Slava0135** [comment]
It is supposed to be played with my other mod - reVision
